### ISSUE TITLE
Ability to translate attributes and states

### ISSUE THREAD

**Issue by robinjhector** [iantrich/config-template-card#102]
**Is your feature request related to a problem? Please describe.**

Not sure

**Describe the solution you'd like**

Some easy way of interpolating the translated strings.

**Describe alternatives you've considered**

N/A

**Additional context**

Given I have sensor, that has a state:
`sensor.ehm6g88s_status` -> `awaiting_start`.

This is translated in the custom component, so how do i get the translated string in my card?

Here's an example:

```yml
- type: custom:config-template-card
  entities:
    - sensor.ehm6g88s_status
  card:
    type: button
    show_name: true
    show_icon: true
    state_color: false
    tap_action:
      action: toggle
    entity: switch.ehm6g88s_smart_charging
    icon: mdi:power
    show_state: false
    name: ${states['sensor.ehm6g88s_status'].state}
```
