### ISSUE TITLE
Camera Image refreshed every time an entity listed for update refresh

### ISSUE THREAD

**Issue by StefanoGiu** [iantrich/config-template-card#107]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.3.6

**Last working release (if known):**
N.A.

**Browser and Operating System:**
Chrome & Unix

**Description of problem:**
I have listed a lot of entities below "entities" tag and some of them refreshes even every 2 seconds... The problem is that the camera images below this config template card, (that are not listed into the entities to be refreshed), every time the update is triggered, are reloaded... and I see constantly the empty box with the loading circle... so the camera images are constantly reloaded even if they should not...

**Comment by ildar170975** [comment]
This is not a bug.
Assume you got a `history-graph` inside `config-template-card` (CTC):
```
type: custom:config-template-card
entities:
  - sensor.my_sensor
card:
  - type: history-graph
    hours_to_show: 72
    entities:
      - sensor.my_sensor
```
This graph will be fully redrawn every time the `sensor.my_sensor` changes.
If not placed inside CTC then the graph just updates a graph's line.

"Solution" - do not place camera image inside CTC.
