### ISSUE TITLE
Card not working with 2022.11

### ISSUE THREAD

**Issue by Kaibob2** [iantrich/config-template-card#114]
**Checklist:**

- X I updated to the latest version available
- X I cleared the cache of my browser

**Release with the issue:** 1.3.6

**Last working release:** 1.3.6 with HA 2022.10

**Browser and Operating System:** Firefox, Edge, Chrome, doesn't matter

**Description of problem:**
I’m having issues with all my config-template-cards. The background image flickers no matter what I try.
The images are stored in /local/rooms/ like they were before.
It appears, that the image disappears for a fracture of a second and comes right back. While the image is gone all icons on the card get crunched in the very top area of the card. I would really appreciate if you could take a look at that and  hopefully fix it asap.
This is the code of one of the cards (the smallest one), as it was working perfectly until 2022.11:

```
card:
  elements:
    - type: custom:cover-icon-element
      entity: cover.werkstatt
      hold_action:
        action: toggle
      tap_action:
        action: more-info
      style:
        left: 38%
        top: 3%
        width: 15%
      color: '#8B4500'
    - conditions:
        - entity: binary_sensor.ble_opening_fenster_werkstatt
          state_not: unavailable
      elements:
        - entity: binary_sensor.ble_opening_fenster_werkstatt
          tap_action:
            action: more-info
          hold_action:
            action: more-info
          icon: >-
            ${if (states['binary_sensor.ble_opening_fenster_werkstatt'].state
            === 'on') 'mdi:window-open';else 'mdi:window-closed'}
          style:
            '--mdc-icon-size': 50px
            color: >-
              ${if (states['binary_sensor.ble_opening_fenster_werkstatt'].state
              === 'on') 'red';else 'white'}
            left: 58%
            top: 3%
          type: icon
      type: conditional
    - type: custom:last-changed-element
      entity: binary_sensor.ble_opening_fenster_werkstatt
      style:
        left: 58.5%
        top: 8%
        color: black
        font-weight: bold
    - entity: light.deckenlampe_werkstatt
      hold_action:
        action: more-info
      tap_action:
        action: toggle
      icon: >-
        ${if (states['light.deckenlampe_werkstatt'].state === 'on')
        'mdi:ceiling-light';else 'mdi:ceiling-light'}
      style:
        '--mdc-icon-size': 80px
        color: >-
          ${if (states['light.deckenlampe_werkstatt'].state === 'on') 'red';else
          'white'}
        left: 50%
        top: 48%
      type: icon
    - entity: climate.heizung_werkstatt
      hold_action:
        action: none
      tap_action:
        action: more-info
      icon: >-
        ${if (states['climate.heizung_werkstatt'].state === 'off')
        'mdi:radiator-off';else 'mdi:radiator' }
      style:
        '--mdc-icon-size': 60px
        color: '${states[''sensor.heizung_werkstatt''].state === ''on'' ? ''red'' : ''blue''}'
        left: 50%
        top: 15%
      type: icon
    - conditions:
        - entity: climate.heizung_werkstatt
          state: heat
      elements:
        - entity: sensor.heizung_werkstatt_status
          hold_action:
            action: none
          tap_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 50%
            top: 10%
          type: state-label
        - entity: climate.heizung_werkstatt
          attribute: current_temperature
          hold_action:
            action: none
          tap_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 65%
            top: 16%
          prefix: 'Ist '
          suffix: °C
          type: state-label
        - entity: climate.heizung_werkstatt
          attribute: temperature
          hold_action:
            action: none
          tap_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 35%
            top: 16%
          prefix: 'Soll '
          suffix: °C
          type: state-label
      type: conditional
    - conditions:
        - entity: sensor.ble_temperature_werkstatt
          state_not: unavailable
        - entity: sensor.ble_temperature_werkstatt
          state_not: unknown
      elements:
        - entity: sensor.ble_temperature_werkstatt
          hold_action:
            action: none
          tap_action:
            action: more-info
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 50%
            top: 30%
          type: state-label
      type: conditional
    - conditions:
        - entity: sensor.ble_humidity_werkstatt
          state_not: unavailable
        - entity: sensor.ble_humidity_werkstatt
          state_not: unknown
      elements:
        - entity: sensor.ble_humidity_werkstatt
          hold_action:
            action: none
          tap_action:
            action: more-info
          style:
            color: >-
              ${if (states['sensor.ble_humidity_werkstatt'].state <= '70')
              'black';else 'red'}
            font-size: 100%
            font-weight: bold
            left: 50%
            top: 38%
          type: state-label
      type: conditional
    - entity: sensor.echo_werkstatt
      hold_action:
        action: navigate
        navigation_path: /lovelace/media
      tap_action:
        action: more-info
      icon: >-
        ${if (states['media_player.werkstatt'].state === 'unavailable')
        'mdi:speaker-off';else 'mdi:speaker' }
      style:
        '--mdc-icon-size': 60px
        color: '${states[''sensor.echo_werkstatt''].state === ''true'' ? ''red'' : ''white''}'
        left: 18%
        top: 25%
      type: icon
  image: /local/rooms/werkstatt.png
  type: picture-elements
entities:
  - climate.heizung_werkstatt
  - light.deckenlampe_werkstatt
  - sensor.heizung_werkstatt
  - sensor.echo_werkstatt
  - sensor.ble_humidity_werkstatt
  - sensor.ble_temperature_werkstatt
  - cover.werkstatt
  - binary_sensor.ble_opening_fenster_werkstatt
type: custom:config-template-card
```

**Additional information:**
That's what the card is supposed to like like:
I can send a screen recording of the issue if this helps.
![bbba4b4c44c089b4965be35de6c12b0e26967b47_2_285x500](https://user-images.githubusercontent.com/20832276/200136890-7ec0f291-6b40-4aee-b673-028695e9c280.jpeg)

**Comment by ildar170975** [comment]
The config-template-card updates itself on every change of any of monitored entities.
It is NOT recommended to place the whole picture elements card into config-template-card.
Use CTC card for a particular element only.

**Comment by SdeGeata** [comment]
@ildar170975: I was having the same problem as you and got the same response. I downgraded HA Core to 2022.10.5 and that fixed it. Admittedly a temporary fix until this problem can be fixed properly.

**Comment by Kaibob2** [comment]
Somehow I don't expect this behavior to be fixed any time soon. The kind of use isn't intended, and I wasn't aware of that. I think I will change the entire code then. This is going to be a huge amount of work, but I suppose it will prevent stuff like this in the future.

**Comment by SdeGeata** [comment]
So you have it too? That’s bad news. I ended up downgrading HA Core to 2022.10.5 to remedy it, at least it works. Please keep me updated on your code change, i will probably need to do the same. So horrible, i only finished my floor-plan lighting days ago, only to have it thwarted by an update.On Nov 6, 2022, at 1:34 PM, Kai ***@***.***> wrote:﻿
Somehow I don't expect this behavior to be fixed any time soon. The kind of use isn't intended, and I wasn't aware of that. I think I will change the entire code then. This is going to be a huge amount of work, but I suppose it will prevent stuff like this in the future.

**Comment by Kaibob2** [comment]
Yes, sure, that's why I openend this issue. I started to convert the cards.
This is "before":


```
card:
  elements:
    - type: custom:cover-icon-element
      entity: cover.kinderzimmer_links
      style:
        left: 25%
        top: 6%
        width: 15%
      color: '#8B4500'
    - conditions:
        - entity: binary_sensor.ble_opening_fenster_kz_links
          state_not: unavailable
      elements:
        - entity: binary_sensor.ble_opening_fenster_kz_links
          tap_action:
            action: more-info
          hold_action:
            action: more-info
          icon: >-
            ${if (states['binary_sensor.ble_opening_fenster_kz_links'].state ===
            'on') 'mdi:window-open';else 'mdi:window-closed'}
          style:
            '--mdc-icon-size': 50px
            color: >-
              ${if (states['binary_sensor.ble_opening_fenster_kz_links'].state
              === 'on') 'red';else 'white'}
            left: 37%
            top: 6%
          type: icon
      type: conditional
    - type: custom:last-changed-element
      entity: binary_sensor.ble_opening_fenster_kz_links
      style:
        left: 37%
        top: 14%
        color: black
        font-weight: bold
    - type: custom:cover-icon-element
      entity: cover.kinderzimmer_rechts
      style:
        left: 68%
        top: 6%
        width: 15%
      color: '#8B4500'
    - conditions:
        - entity: binary_sensor.ble_opening_fenster_kz_rechts
          state_not: unavailable
      elements:
        - entity: binary_sensor.ble_opening_fenster_kz_rechts
          tap_action:
            action: more-info
          hold_action:
            action: more-info
          icon: >-
            ${if (states['binary_sensor.ble_opening_fenster_kz_rechts'].state
            === 'on') 'mdi:window-open';else 'mdi:window-closed'}
          style:
            '--mdc-icon-size': 50px
            color: >-
              ${if (states['binary_sensor.ble_opening_fenster_kz_rechts'].state
              === 'on') 'red';else 'white'}
            left: 80%
            top: 6%
          type: icon
      type: conditional
    - type: custom:last-changed-element
      entity: binary_sensor.ble_opening_fenster_kz_rechts
      style:
        left: 80%
        top: 14%
        color: black
        font-weight: bold
    - entity: light.deckenlampe_kinderzimmer
      hold_action:
        action: more-info
      icon: >-
        ${if (states['light.deckenlampe_kinderzimmer'].state === 'on')
        'mdi:ceiling-light';else 'mdi:ceiling-light'}
      style:
        '--mdc-icon-size': 80px
        color: >-
          ${if (states['light.deckenlampe_kinderzimmer'].state === 'on')
          'red';else 'white'}
        left: 50%
        top: 50%
      tap_action:
        action: toggle
      type: icon
    - entity: switch.sternenhimmel
      hold_action:
        action: more-info
      icon: >-
        ${if (states['switch.sternenhimmel'].state === 'on')
        'mdi:star-four-points';else 'mdi:star-four-points-outline'}
      style:
        '--mdc-icon-size': 60px
        color: >-
          ${if (states['switch.sternenhimmel'].state === 'on') 'red';else
          'white'}
        left: 13%
        top: 86%
      tap_action:
        action: toggle
      type: icon
    - entity: light.stehlampe_kinderzimmer
      hold_action:
        action: o
      icon: >-
        ${if (states['light.stehlampe_kinderzimmer'].state === 'on')
        'mdi:floor-lamp';else 'mdi:floor-lamp'}
      style:
        '--mdc-icon-size': 80px
        color: >-
          ${if (states['light.stehlampe_kinderzimmer'].state === 'on')
          'red';else 'white'}
        left: 10%
        top: 13%
      tap_action:
        action: toggle
      type: icon
    - entity: climate.heizung_kinderzimmer
      hold_action:
        action: navigate
        navigation_path: /lovelace/heizung
      icon: >-
        ${if (states['climate.heizung_kinderzimmer'].state === 'off')
        'mdi:radiator-off';else 'mdi:radiator' }
      style:
        '--mdc-icon-size': 60px
        color: >-
          ${states['sensor.heizung_kinderzimmer'].state === 'on' ? 'red' :
          'blue'}
        left: 50%
        top: 25%
      tap_action:
        action: more-info
      type: icon
    - conditions:
        - entity: climate.heizung_kinderzimmer
          state: heat
      elements:
        - entity: sensor.heizung_kinderzimmer_status
          hold_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 50%
            top: 16%
          tap_action:
            action: none
          type: state-label
        - entity: climate.heizung_kinderzimmer
          attribute: current_temperature
          hold_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 68%
            top: 27%
          prefix: 'Ist '
          suffix: °C
          tap_action:
            action: none
          type: state-label
        - entity: climate.heizung_kinderzimmer
          attribute: temperature
          hold_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 32%
            top: 27%
          prefix: 'Soll '
          suffix: °C
          tap_action:
            action: none
          type: state-label
      type: conditional
    - conditions:
        - entity: sensor.ble_temperature_kinderzimmer
          state_not: unavailable
        - entity: sensor.ble_temperature_kinderzimmer
          state_not: unknown
      elements:
        - entity: sensor.ble_temperature_kinderzimmer
          tap_action:
            action: more-info
          hold_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 15%
            top: 40%
          type: state-label
      type: conditional
    - conditions:
        - entity: sensor.ble_humidity_kinderzimmer
          state_not: unavailable
        - entity: sensor.ble_humidity_kinderfzimmer
          state_not: unknown
      elements:
        - entity: sensor.ble_humidity_kinderzimmer
          tap_action:
            action: more-info
          hold_action:
            action: none
          style:
            color: black
            font-size: 100%
            font-weight: bold
            left: 15%
            top: 49%
          type: state-label
      type: conditional
    - conditions:
        - entity: binary_sensor.wifi_steckdose_5_verbindung
          state: 'on'
      elements:
        - entity: light.nachtlicht_kizi
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          icon: mdi:weather-night
          style:
            '--mdc-icon-size': 50px
            color: >-
              ${states['light.nachtlicht_kizi'].state === 'on' ? 'red' :
              'white'}
            left: 50%
            top: 9%
          type: icon
      type: conditional
  image: /local/rooms/kinderzimmer.png
  type: picture-elements
entities:
  - climate.heizung_kinderzimmer
  - sensor.tempkinderzimmer
  - sensor.heizung_kinderzimmer
  - sensor.ble_humidity_kinderzimmer
  - sensor.ble_temperature_kinderzimmer
  - cover.kinderzimmer_links
  - cover.kinderzimmer_rechts
  - light.nachtlicht_kizi
  - light.stehlampe_kinderzimmer
  - light.deckenlampe_kinderzimmer
  - binary_sensor.ble_opening_fenster_kz_rechts
  - binary_sensor.ble_opening_fenster_kz_links
type: custom:config-template-card
```

and this is "after":

```
type: picture-elements
image: /local/rooms/kinderzimmer.png
elements:
  - type: custom:cover-icon-element
    entity: cover.kinderzimmer_links
    style:
      left: 25%
      top: 6%
      width: 15%
    color: '#8B4500'
  - conditions:
      - entity: binary_sensor.ble_opening_fenster_kz_links
        state_not: unavailable
    elements:
      - entity: binary_sensor.ble_opening_fenster_kz_links
        tap_action:
          action: more-info
        hold_action:
          action: more-info
        style:
          left: 34%
          top: 1%
          transform: scale(2)
        type: state-icon
    type: conditional
  - type: custom:last-changed-element
    entity: binary_sensor.ble_opening_fenster_kz_links
    style:
      left: 38.5%
      top: 14%
      color: black
      font-weight: bold
  - type: custom:cover-icon-element
    entity: cover.kinderzimmer_rechts
    style:
      left: 68%
      top: 6%
      width: 15%
    color: '#8B4500'
  - conditions:
      - entity: binary_sensor.ble_opening_fenster_kz_rechts
        state_not: unavailable
    elements:
      - entity: binary_sensor.ble_opening_fenster_kz_rechts
        tap_action:
          action: more-info
        hold_action:
          action: more-info
        style:
          left: 76%
          top: 1%
          transform: scale(2)
        type: state-icon
    type: conditional
  - type: custom:last-changed-element
    entity: binary_sensor.ble_opening_fenster_kz_rechts
    style:
      left: 80.5%
      top: 14%
      color: black
      font-weight: bold
  - entity: light.deckenlampe_kinderzimmer
    hold_action:
      action: more-info
    style:
      left: 45%
      top: 50%
      transform: scale(3)
    tap_action:
      action: toggle
    type: state-icon
  - entity: switch.sternenhimmel
    hold_action:
      action: more-info
    icon: mdi:star-four-points-outline
    style:
      left: 9%
      top: 83%
      transform: scale(2.5)
    tap_action:
      action: toggle
    type: state-icon
  - entity: light.stehlampe_kinderzimmer
    hold_action:
      action: more-info
    style:
      left: 5%
      top: 8%
      transform: scale(3)
    tap_action:
      action: toggle
    type: state-icon
  - type: custom:config-template-card
    entities:
      - climate.heizung_kinderzimmer
    element:
      type: icon
      entity: climate.heizung_kinderzimmer
      icon: >-
        ${if (states['climate.heizung_kinderzimmer'].state === 'off')
        'mdi:radiator-off';else 'mdi:radiator' }
      style:
        '--mdc-icon-size': 60px
        color: >-
          ${states['sensor.heizung_kinderzimmer'].state === 'on' ? 'red' :
          'blue'}
      tap_action:
        action: more-info
      hold_action:
        action: navigate
        navigation_path: /lovelace/heizung
    style:
      left: 50%
      top: 27%
  - conditions:
      - entity: climate.heizung_kinderzimmer
        state: heat
    elements:
      - entity: sensor.heizung_kinderzimmer_status
        hold_action:
          action: none
        style:
          color: black
          font-size: 100%
          font-weight: bold
          left: 50%
          top: 18%
        tap_action:
          action: none
        type: state-label
      - entity: climate.heizung_kinderzimmer
        attribute: current_temperature
        hold_action:
          action: none
        style:
          color: black
          font-size: 100%
          font-weight: bold
          left: 68%
          top: 29%
        prefix: 'Ist '
        suffix: °C
        tap_action:
          action: none
        type: state-label
      - entity: climate.heizung_kinderzimmer
        attribute: temperature
        hold_action:
          action: none
        style:
          color: black
          font-size: 100%
          font-weight: bold
          left: 32%
          top: 29%
        prefix: 'Soll '
        suffix: °C
        tap_action:
          action: none
        type: state-label
    type: conditional
  - conditions:
      - entity: sensor.ble_temperature_kinderzimmer
        state_not: unavailable
      - entity: sensor.ble_temperature_kinderzimmer
        state_not: unknown
    elements:
      - entity: sensor.ble_temperature_kinderzimmer
        tap_action:
          action: more-info
        hold_action:
          action: none
        style:
          color: black
          font-size: 100%
          font-weight: bold
          left: 15%
          top: 40%
        type: state-label
    type: conditional
  - conditions:
      - entity: sensor.ble_humidity_kinderzimmer
        state_not: unavailable
      - entity: sensor.ble_humidity_kinderfzimmer
        state_not: unknown
    elements:
      - entity: sensor.ble_humidity_kinderzimmer
        tap_action:
          action: more-info
        hold_action:
          action: none
        style:
          color: black
          font-size: 100%
          font-weight: bold
          left: 15%
          top: 49%
        type: state-label
    type: conditional
  - conditions:
      - entity: binary_sensor.wifi_steckdose_5_verbindung
        state: 'on'
    elements:
      - entity: light.nachtlicht_kizi
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        icon: mdi:weather-night
        style:
          left: 48%
          top: 4%
          transform: scale(2)
        type: state-icon
    type: conditional
```
The look stays the same, but the flickering is gone!

![SharedScreenshot](https://user-images.githubusercontent.com/20832276/200319486-48b6cb70-01fe-4179-a15c-12c5e8a04dbf.jpg)
