### ISSUE TITLE
Value template/Jinja not working as expected

### ISSUE THREAD

**Issue by kromadg** [iantrich/config-template-card#121]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.3.6

**Last working release (if known):**

**Browser and Operating System:**
Chrome 109.0.5414.120 (Official version) 64 bits
Windows 11 22H2, Compilation 22621.1105

**Description of problem:**

Trying to render an iframe to grafana with dynamically set timestamp. 

When put values in `variables` section in "value_template"/Jinja format not working as expected.

Examples:

***Doesn't work:***
```
type: custom:config-template-card
variables:
  FROM: >
    {{ as_timestamp(now()) }}
entities:
  - sensor.gps_latitude_clean
  - sensor.gps_longitude_clean
card:
  type: iframe
  url: >-
    ${"https://exampleurl/api/hassio_ingress/xxx-yyy/d-solo/zzz/grafana-dash?orgId=1&from="+FROM+"&panelId=4"}
  aspect_ratio: 50%
```

If put a straight timestamp value, works.

***This works:***
```
type: custom:config-template-card
variables:
  FROM: >
    {{ 1674850557126 }}
entities:
  - sensor.gps_latitude_clean
  - sensor.gps_longitude_clean
card:
  type: iframe
  url: >-
    ${"https://exampleurl/api/hassio_ingress/xxx-yyy/d-solo/zzz/grafana-dash?orgId=1&from="+FROM+"&panelId=4"}
  aspect_ratio: 50%
```

**Javascript errors shown in the web inspector (if applicable):**

```
config-template-card.js?hacstag=172177543136:252 Uncaught (in promise) ReferenceError: as_timestamp is not defined
    at eval (eval at _evaluateTemplate (config-template-card.js?hacstag=172177543136:905:34), <anonymous>:1:4)
    at ConfigTemplateCard._evaluateTemplate (config-template-card.js?hacstag=172177543136:905:34)
    at config-template-card.js?hacstag=172177543136:860:40
    at Array.forEach (<anonymous>)
    at ConfigTemplateCard._evaluateConfig (config-template-card.js?hacstag=172177543136:849:32)
    at ConfigTemplateCard.render (config-template-card.js?hacstag=172177543136:807:23)
    at ConfigTemplateCard.update (config-template-card.js?hacstag=172177543136:265:321)
    at ConfigTemplateCard.performUpdate (config-template-card.js?hacstag=172177543136:252:4796)
    at ConfigTemplateCard.scheduleUpdate (config-template-card.js?hacstag=172177543136:252:4443)
    at ConfigTemplateCard._$EC (config-template-card.js?hacstag=172177543136:252:4351)
```

**Additional information:**

**Comment by ildar170975** [comment]
you CANNOT use jinjia inside JS code - as well as jinjia HA extensions, as well as things like is_state(), state_attr() etc.

**Comment by kromadg** [comment]
Sorry. I think I missed that part of the doc.

**Comment by UlrichThiess** [comment]
```
type: custom:config-template-card
variables:
  LAT: >-
    state_attr("device_tracker.ulrichs_iphone_11_pro_app","latitude") | float |
    round(3)
  LON: >-
    state_attr("device_tracker.ulrichs_iphone_11_pro_app","longitude") | float |
    round(3)
entities:
  - device_tracker.ulrichs_iphone_11_pro_app
card:
  type: iframe
  url: ${"https://httpbin.org/get?" + LAT}
  aspect_ratio: 150%
```

What do im doing wrong?
