### ISSUE TITLE
Use variable in entity id

### ISSUE THREAD

**Issue by flouck** [iantrich/config-template-card#130]
I have many radiators having a dedicated name each of them. I have a dropdown list for users to select the radiator they want to visualize. I would like the vairable to be inside the entity id. Is it already possible?
```entity: ${climate.radiator_RADIATOR}```
or something like that :
```entity: climate.radiator_${RADIATOR}```

**Comment by ildar170975** [comment]
Both your variants are wrong.
The 2nd variant MAY work with https://github.com/iantrich/config-template-card/pull/110 (have not checked).
Use smth like:
```
${"climate.radiator_" + RADIATOR}
```

**Comment by flouck** [comment]
Yes it works, thank you! Is there a way to transform the variable in that way:
- all spaces become underscores
- all capital letters become small letters

Otherwise, HA does not recognize the entity id. Last solution would be to modify the names in the dropdown list but I wanted to keep them as they are for aesthetic reasons 😊

Mathieu
________________________________

**Comment by ildar170975** [comment]
> Is there a way to transform the variable in that way:

Use JS to make required transformations.

**Comment by hitnrun30** [comment]
OK, i have something similar but cant get it to work.
I created a select template with the values of my remotes.  I want to 

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: select.chromecast_devices
        name: Select Chromecast
    show_header_toggle: false
  - type: custom:config-template-card
    variables:
      - states['select.chromecast_devices'].state
    entities:
      - select.chromecast_devices
    card:
      type: entities
      entities:
        - entity: ${"select.chromecast_devices"} 
```

How do I get it to make the entity the value of the select?

**Comment by hitnrun30** [comment]
Is there any way you can help me.  I have a bunch of chromecasts and would ove to be able to switch between them.
I created a select template with the values of my remotes.
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: select.chromecast_devices
        name: Select Chromecast
    show_header_toggle: false
  - type: custom:config-template-card
    variables:
      - states['select.chromecast_devices'].state
    entities:
      - select.chromecast_devices
    card:
      type: entities
      entities:
        - entity: ${"select.chromecast_devices"} 
```

How do I get it to make the entity the value of the select?
