### ISSUE TITLE
Gauge graph without needle incorrectly displayed

### ISSUE THREAD

**Issue by Haluska77** [iantrich/config-template-card#143]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.3.6
**Last working release (if known):**
none
**Browser and Operating System:**
win - Chrome
win - Edge

**Description of problem:**
Having gauge graph displaying solar production distributed to home or grid

type: custom:config-template-card
entities:
  - sensor.solar_production
  - sensor.grid_import
card:
  type: gauge
  entity: sensor.solar_production
  name: Solar production to home / grid
  unit: W
  min: 0
  needle: true
  max: ${states["sensor.solar_production"].state}
  segments:
    - from: 0 (HOME)
      color: '#ffa600'
    - from: >- (GRID)
        ${states["sensor.solar_production"].state -
        states["sensor.grid_import"].state}
      color: '#8353d1'

After removing needle from graph (needle:false), it does incorrectly display graph and displays whole graph as a grid part.
![solar_graph_correct](https://github.com/user-attachments/assets/30fe6c34-9459-40c3-b90f-3c31d59a43a1)
![solar_graph_incorrect](https://github.com/user-attachments/assets/407897eb-6a56-4d9d-9b11-45f260261357)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ildar170975** [comment]
Suggest you to post a FORMATTED code - currently your code cannot be analysed.
Check other issues for examples.

**Comment by Haluska77** [comment]
Here it is:

```
type: custom:config-template-card
entities:
  - sensor.solar_production
  - sensor.grid_import
card:
  type: gauge
  entity: sensor.solar_production
  name: Solar production to home / grid
  unit: W
  min: 0
  needle: true
  max: ${states["sensor.solar_production"].state}
  segments:
    - from: 0
      color: '#ffa600'
    - from: >-
        ${states["sensor.solar_production"].state -
        states["sensor.grid_import"].state}
      color: '#8353d1'

```
