### ISSUE TITLE
Global Variables not working

### ISSUE THREAD

**Issue by artwhitehead** [iantrich/config-template-card#152]
Global variables (and functions) does not seem to be working for me.  I found a similar post online with someone else having this issue, but it was never answered.  So if I declare:

```
title: Kiosk

config_template_card_vars:
  someText: "something"
  rotateHue: |
    light =>{
      return "hue-rotate(" + (states[light].attributes.hs_color ?
      states[light].attributes.hs_color[0] - 28 : 0) +"deg) " +
      "saturate(" + (states[light].attributes.hs_color ?
      states[light].attributes.hs_color[1] : 100) + "%"
    }

views:
```

and later call for someText....

```
- type: custom:config-template-card
                    entities:
                      - light.basement_can_1
                    element:
                      type: image
                      entity: light.basement_can_1
                      action: none
                      tap_action: none
                      hold_action: none
                      double_tap_action: none
                      image: /local/kiosk/VZB_light_can1_ww.png
                    style:
                      top: 70.83333%
                      left: 32.78646%
                      width: 51.30208%
                      pointer-events: none
                      mix-blend-mode: lighten
                      opacity: "${states['light.basement_can_1'].state === 'on' ? (states['light.basement_can_1'].attributes.brightness / 255) : '0'}"
                      filter: ${console.log("whatever " + someText);}
```

someText shows up as 'undefined'

Obviously I want to use the rotateHue function and not just output text to the console, but I added that section just to see if the global variables were working.  They were not.  If I call rotateHue, it also says that it is undefined.  As far as I know, I'm putting the global variables in the correct place, they just don't seem to be finding them.  If I put the code under variables in the config-template-card itself, the function works.  But there wouldn't be much point to putting it there as there are many overlays and using the function globally would be the whole point of creating the function in the first place.

**Comment by ildar170975** [comment]
1. You declared global variables. Have you tested your variables if they are declared as "local" - i.e. inside the card itself? If your vars do not work - why the issue is about "global vars" then? Then may be the variables are defined in a wrong way?
2. Using config-template-card to define variables to be used inside card-mod code is absolutely not needed. Card-mod itself supports jinja. **UPDATE: my mistake, this remark is unrelated since OP is not using card-mod, this is a picture-elements card.**

Suggest you to ask question in the main thread in Community if you have any doubts: https://community.home-assistant.io/t/100-templatable-lovelace-configurations/105241

> If I put the code under variables in the config-template-card itself, the function works

But the "someText" is definitely defined in a wrong way - and will not work in case of global or "local" vars.
It must be 
```
someText: '''something'''
```
So - suggest to double-check again with "local" vars.

**Comment by artwhitehead** [comment]
The point wasn't to get the text 'Something', it was to run the function rotateHue.  I added the text to see if variables that were declared globally was actually working.  Which it was not.  To keep it even simpler, here's a simple test page:

```
# test.yaml

views:
  - title: Test
    type: panel
    theme: home

    cards:
      - type: picture-elements
        image: /local/kiosk/VZB_lights_off.png
        elements:
          - type: custom:config-template-card
            variables:
              someText: "'something'"
            entities:
              - light.hue_color_lamp_1
            element:
              type: image
              entity: light.hue_color_lamp_1
              action: none
              tap_action: none
              hold_action: none
              double_tap_action: none
              image:  /local/kiosk/VZB_light_office_w.png
            style:
              top: 70.52083%
              left: 51.22396%
              width: 16.09375%
              pointer-events: none
              mix-blend-mode: lighten
              opacity: "${states['light.hue_color_lamp_1'].state === 'on' ? (states['light.hue_color_lamp_1'].attributes.brightness / 255) : '0'}"
              filter: "${console.log(someText);}"
```

When I load the page, the text 'something' is output to the console.  If I write the page as:

```
# test.yaml
config_template_card_vars:
  someText: "'something'"

views:
  - title: Test
    type: panel
    theme: home

    cards:
      - type: picture-elements
        image: /local/kiosk/VZB_lights_off.png
        elements:
          - type: custom:config-template-card
            entities:
              - light.hue_color_lamp_1
            element:
              type: image
              entity: light.hue_color_lamp_1
              action: none
              tap_action: none
              hold_action: none
              double_tap_action: none
              image:  /local/kiosk/VZB_light_office_w.png
            style:
              top: 70.52083%
              left: 51.22396%
              width: 16.09375%
              pointer-events: none
              mix-blend-mode: lighten
              opacity: "${states['light.hue_color_lamp_1'].state === 'on' ? (states['light.hue_color_lamp_1'].attributes.brightness / 255) : '0'}"
              filter: "${console.log(someText);}"
```
I get the following message in the console:

Uncaught (in promise) ReferenceError: someText is not defined  ...   config-template-card.js?hacstag=172177543136

Same thing goes for the rotateHue function (when included).  If I am going to have multiple images as overlays using the config-template-card, it makes sense to have this function as a global function, since I will be calling it from various cards.

**Comment by ildar170975** [comment]
> I added the text to see if variables that were declared globally was actually working. Which it was not

Please check this example:
```
config_template_card_vars:
  ctc_varSTRING_1: '''xxxx'''
  ctc_varSTRING_2: "'yyyy'"
```
```
title: ...
path: ...
cards:
  - type: custom:config-template-card
    entities:
      - sun.sun
    card:
      type: entities
      entities:
        - entity: sun.sun
          name: ${ctc_varSTRING_1}
        - entity: sun.sun
          name: ${ctc_varSTRING_2}
```
![image](https://github.com/user-attachments/assets/03e9f0d0-bf7c-4088-925d-8fd268ab2d4d)

Are you sure that variables are declared properly?

Suggest you to test with a SIMPLE code.
Otherwise you adding zillions of other interfering factors which distract you.
Like this:
```
filter: "${console.log(someText);}"
```
which is also not correct since a WHOLE string (here - a whole "style" option) must be a template (not to mention that a "filter" must be a CSS value, not some js command). Hope you are not using some kind of chatgpt or other AI which generate a BS.

Here is a proper syntax for a simplest style:
```
      foo: >-
        color =>{
          return "ha-card { border: 1px solid " + color + ";}"
        }
````
```
card_mod:
  style: '${foo("red")}'
```
which ofc will be a bit cumbersome in your case with many styles. And once again - config-template-card is not supposed to be used for card-mod.
UPDATE: my mistake, all card-mod related remarks are unrelated since OP is not using card-mod, this is a picture-elements card.

**Comment by artwhitehead** [comment]
Used your simple code and get the same type of error

Uncaught (in promise) ReferenceError: ctc_varSTRING_1 is not defined

So, for some reason, the config_template_card_vars: line is not creating global variables in my case.  For reference, this is the entire page of code:

```
# test.yaml
config_template_card_vars:
  ctc_varSTRING_1: '''xxxx'''
  ctc_varSTRING_2: "'yyyy'"

views:
  - title: Test
    type: masonry
    theme: home

    cards:
      - type: custom:config-template-card
        entities:
          - sun.sun
        card:
          type: entities
          entities:
            - entity: sun.sun
              name: ${ctc_varSTRING_1}
            - entity: sun.sun
              name: ${ctc_varSTRING_2}
```

Thanks.
