### ISSUE TITLE
[support] vertical stack and custom cards

### ISSUE THREAD

**Issue by prankousky** [iantrich/config-template-card#162]
Hi,

I have tried and tried, but I just cannot figure out how to do this, can you please help me?

The code below has been adapted to my original card (further below), trying to follow the `README.md`, but it does not work.

While posting this, I realize there is some issue with the variables / code in the individual card, I shouldn't have used `states[...].state`, but just the entity itself instead; but that is not the reason this doesn't work. For example, even the heading (which should be `Arbeitszimmer` only displays `${ROOM_NAME}`, though I expected it to use the value from the variable.

```yaml
type: 'custom:config-template-card'
variables:
  ROOM_NAME: "Arbeitszimmer"
  ROOM_ICON: "mdi:chair-rolling"
  ROOM_LINK: "/dashboard-shared/unten-arbeitszimmer"
  DOOR: states['binary_sensor.unten_arbeitszimmer_tuer_contact'].state
  WINDOW: states['binary_sensor.unten_arbeitszimmer_fenster_contact'].state
entities:
  - light.schwenker

type: vertical-stack
cards:
  - type: custom:banner-card
    heading:
      - ${ROOM_ICON}
      - "${ROOM_NAME}"
    link: ${ROOM_LINK}
    background: "#999999"
    color: "#000000"
  - type: vertical-stack
    cards:
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:paper-buttons-row
            buttons:
              - entity_id: script.dummy
                icon: >
                  {% set tuer = ${DOOR} %}

                  {% if (tuer) == "off" %}

                  mdi:door-closed

                  {% else %}

                  mdi:door-open

                  {% endif %}
                name: >
                  {% from 'easy_time.jinja' import easy_time %} {{
                  easy_time(states.${DOOR}.last_changed,
                  short=True) }}
                layout: icon|name
                style:
                  button:
                    font-size: 12px
                    padding: 7px 0px 7px 0px
                    color: var(--nav-color)
                    border-bottom: 0px solid
                  icon:
                    "--mdc-icon-size": 30px
                    color: >
                      {% set tuer = ${DOOR} %}

                      {% if (tuer) == "off" %}

                      #00EBB4

                      {% else %}

                      white

                      {% endif %}
                  name:
                    font-size: 10px;
                    font-weight: 1000
                    margin-bottom: 10px
                    margin-left: "-5px"
                    color: white
                    height: 20px
                    width: 20px
                    border-radius: 50%
                    z-index: 1
                    padding: 2px 2px 2px 3px
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.more_info
                    data:
                      entity: ${DOOR}
                hold_action:
                  action: none
              - entity_id: script.dummy
                icon: >
                  {% set fenster = ${WINDOW} %}

                  {% if (fenster) == "on" %}

                  mdi:window-open

                  {% else %}

                  mdi:window-closed

                  {% endif %}
                name: >
                  {% from 'easy_time.jinja' import easy_time %} {{
                  easy_time(states.${WINDOW}.last_changed,
                  short=True) }}
                layout: icon|name
                style:
                  button:
                    font-size: 12px
                    padding: 7px 0px 7px 0px
                    color: var(--nav-color)
                    border-bottom: 0px solid
                  icon:
                    "--mdc-icon-size": 30px
                    color: >
                      {% set fenster = ${WINDOW} %} {%
                      if (fenster) == "off" %} #00EBB4 {% else %} white {% endif
                      %}
                  name:
                    font-size: 10px;
                    font-weight: 1000
                    margin-bottom: 10px
                    margin-left: "-5px"
                    color: white
                    height: 20px
                    width: 20px
                    border-radius: 50%
                    z-index: 1
                    padding: 2px 2px 2px 3px
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.more_info
                    data:
                      entity: ${WINDOW}
                hold_action:
                  action: none
```

And below is the corresponding code of the original card that works. The card itself has way more content than this, but I am trying to keep it short. There is one card like this per room, and I'd like to only switch the variables at the very top of the (firstly pasted) code in order to generate each individual card.

```yaml
type: vertical-stack
cards:
  - type: custom:banner-card
    heading:
      - mdi:chair-rolling
      - "${NAME}"
    link: /dashboard-shared/unten-arbeitszimmer
    background: "#999999"
    color: "#000000"
  - type: vertical-stack
    cards:
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:paper-buttons-row
            buttons:
              - entity_id: script.dummy
                icon: >
                  {% set tuer =
                  states("binary_sensor.unten_arbeitszimmer_tuer_contact") %}

                  {% if (tuer) == "off" %}

                  mdi:door-closed

                  {% else %}

                  mdi:door-open

                  {% endif %}
                name: >
                  {% from 'easy_time.jinja' import easy_time %} {{
                  easy_time(states.binary_sensor.unten_arbeitszimmer_tuer_contact.last_changed,
                  short=True) }}
                layout: icon|name
                style:
                  button:
                    font-size: 12px
                    padding: 7px 0px 7px 0px
                    color: var(--nav-color)
                    border-bottom: 0px solid
                  icon:
                    "--mdc-icon-size": 30px
                    color: >
                      {% set tuer =
                      states("binary_sensor.unten_arbeitszimmer_tuer_contact")
                      %}

                      {% if (tuer) == "off" %}

                      #00EBB4

                      {% else %}

                      white

                      {% endif %}
                  name:
                    font-size: 10px;
                    font-weight: 1000
                    margin-bottom: 10px
                    margin-left: "-5px"
                    color: white
                    height: 20px
                    width: 20px
                    border-radius: 50%
                    z-index: 1
                    padding: 2px 2px 2px 3px
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.more_info
                    data:
                      entity: binary_sensor.unten_arbeitszimmer_tuer_contact
                hold_action:
                  action: none
              - entity_id: script.dummy
                icon: >
                  {% set fenster =
                  states("binary_sensor.gruppe_arbeitszimmer_fenster") %}

                  {% if (fenster) == "on" %}

                  mdi:window-open

                  {% else %}

                  mdi:window-closed

                  {% endif %}
                name: >
                  {% from 'easy_time.jinja' import easy_time %} {{
                  easy_time(states.binary_sensor.gruppe_arbeitszimmer_fenster.last_changed,
                  short=True) }}
                layout: icon|name
                style:
                  button:
                    font-size: 12px
                    padding: 7px 0px 7px 0px
                    color: var(--nav-color)
                    border-bottom: 0px solid
                  icon:
                    "--mdc-icon-size": 30px
                    color: >
                      {% set fenster =
                      states("binary_sensor.gruppe_arbeitszimmer_fenster") %} {%
                      if (fenster) == "off" %} #00EBB4 {% else %} white {% endif
                      %}
                  name:
                    font-size: 10px;
                    font-weight: 1000
                    margin-bottom: 10px
                    margin-left: "-5px"
                    color: white
                    height: 20px
                    width: 20px
                    border-radius: 50%
                    z-index: 1
                    padding: 2px 2px 2px 3px
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.more_info
                    data:
                      entity: binary_sensor.gruppe_arbeitszimmer_fenster
                hold_action:
                  action: none    
```

Can you please help me figure this out? I am trying to renew my main lovelace configuration. Doing this for each and every room is very bothersome, even with search and replace in the editor, so it'd be so nice if I could utilize `config-template-card` to simplify it.

Thank you in advance for your help :)
