### ISSUE TITLE
Using several templates in a string may cause errors

### ISSUE THREAD

**Issue by ildar170975** [iantrich/config-template-card#166]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
1.3.7-beta.1

**Last working release (if known):**

**Browser and Operating System:**
Chrome 134.0.6998.36 
Win10x64

**Description of problem:**

Consider this example:
```
type: vertical-stack
cards:
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: ${VAR}
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: '${VAR}'
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: "${VAR}"
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: >-
        ${VAR}
```
All cards only differ in a way of using a template:
-- no quotes
-- in single quotes
-- in double quotes
-- with `>-` multiline-yaml syntax

Results are same correct:
![Image](https://github.com/user-attachments/assets/6f7ba189-6b9e-4262-bde4-0b92af1d4a1d)

Now let's test with several templates in a string:
```
type: vertical-stack
cards:
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: ${VAR} ${VAR}
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: '${VAR} ${VAR}'
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: "${VAR} ${VAR}"
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: >-
        ${VAR} ${VAR}
```
In all cases it gives an error:
![Image](https://github.com/user-attachments/assets/4c760fe4-6913-40fe-b200-6db9303f3d34)

Using more quotes gives a result - but values are embraced by quotes:
```
type: vertical-stack
cards:
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: '''${VAR} ${VAR}'''
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: "'${VAR} ${VAR}'"
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: '"${VAR} ${VAR}"'
  - type: custom:config-template-card
    entities:
      - sun.sun
    variables:
      VAR: states['sun.sun'].state
    card:
      type: markdown
      content: >-
        '${VAR} ${VAR}'
```

![Image](https://github.com/user-attachments/assets/dd61d87c-6352-406f-8803-6e6aefc409fa)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
