### ISSUE TITLE
HUE Scenes

### ISSUE THREAD

**Issue by xHecktor** [iantrich/config-template-card#170]
`Hey` iantrich,

I would like to use your map to automatically read out HUE scenes in the attributes and then display them as buttons in a horizontal slider or as a grid.
The aim is to automatically display newly created scenes with the hue app in the HA dashboard

Example entity:
light.jan_az_2

```
Attribute:
  min_color_temp_kelvin: 2202
  max_color_temp_kelvin: 6535
  min_mireds: 153
  max_mireds: 454
  supported_color_modes: color_temp, xy
  color_mode: color_temp
  brightness: 255
  color_temp_kelvin: 4000
  color_temp: 250
  hs_color: 26.812, 34.87
  rgb_color: 255, 206, 166
  xy_color: 0.42, 0.365
  is_hue_group: true
  hue_scenes: Color Burst, Nordlichter, Hell, Verträumter Sonnenuntergang, Nachtlicht, Unter dem Baum, Ruhephase, Krokus, Kühl hell, Natürliches Licht, Miami, Rio, Entspannen
  hue_type: room
  lights: Hue Play 1, Hue Play 2, Jan AZ
  entity_id: light.hue_play_2, light.jan_az, light.hue_play_1
  dynamics: false
  icon: mdi:lightbulb-group
  friendly_name: Jan AZ
  supported_features: 40
```

the following code correctly lists the scenes:
```
type: markdown
entity_id: light.jan_az_2
content: "{{ states.light.jan_az_2.attributes.hue_scenes }}"
```

Result:
Color Burst,Nordlichter,Hell,Verträumter Sonnenuntergang,Miami,Nachtlicht,Unter dem Baum,Ruhephase,Krokus,Natürliches Licht,Kühl hell,Rio,Entspannen

I currently use the following code in the dashboard (manuell)

```
  type: vertical-stack
  cards:
    - square: false
      type: grid
      columns: 3
      title: Szenen
      cards:
        - type: tile
          entity: scene.jan_az_naturliches_licht
          hide_state: true
          tap_action:
            action: toggle
          name: Natürliches Licht
          vertical: true
        - type: tile
          entity: scene.jan_az_hell
          hide_state: true
          tap_action:
            action: toggle
          name: Hell
```

So far I have only received code errors or blank cards. Can you help me here? Thanks

```
type: 'custom:config-template-card'
variables:
 
  SCENES: states['light.jan_az_2'].attributes.hue_scenes
    ? states['light.jan_az_2'].attributes.hue_scenes.split(',')
    : []
entities:

  - light.jan_az_2

card:
  type: vertical-stack

  cards: >
    ${SCENES.map(scene => `
    - type: tile
      # Wir bauen den Scene-Entity-Namen, z.B. "scene.jan_az_color_burst"
      entity: scene.jan_az_${scene.trim().toLowerCase().replace(/ /g, "_")}
      name: "${scene.trim()}"
      tap_action:
        action: toggle
      vertical: true
    `).join('')}
```
