### ISSUE TITLE
[FR] Support the usage of "energy-date-selection"

### ISSUE THREAD

**Issue by carvalr** [iantrich/config-template-card#174]
I have tried using a `energy-date-selection` to set the range for a `custom:map-card` inside the `config-template-card`.
I have an specific scenario where I have to use the config-template-card to handle my entities name dynamically. Based on this, consider the code showed below only for sample purpose only.

When using the `map-card` and the `energy-date-selection` it works properly, but when adding then in a `config-template-card` the history stops working because `energy-date-selection` cannot be managed by `config-template-card`.

The request is to make possible to use the 'energy-date-selection` card.
Is there anyway - except getting rid of `energy-date-selection` - to make it work?

```
type: custom:config-template-card
entities:
  - device_tracker.my_device
card:
  type: grid
  square: false
  cards:
    - type: custom:map-card
      history_date_selection: true
      entities:
        - entity: device_tracker.my_device
      card_mod:
        style: |
          ha-card {
            margin-top: -10px;
          }
          ha-card #map {
            height:calc(100vh - 56px);
            border-radius:0;
          }
    - type: energy-date-selection
      card_mod:
        style: |
          ha-card {
                z-index: 1;
                position: absolute;
                height: 80px !important;
                width: 80%;
                top: 75px;
                right: 10px;
                max-width: 450px;
          }
  columns: 1
```

Left side: using config-template-card
Right side: not using config-template-card

![Image](https://github.com/user-attachments/assets/65ad6b02-675f-4186-a4eb-2109a990f544)

**Comment by ildar170975** [comment]
1. Please always post a code formatted (triple "`" backticks) & omit unneeded parts.
2. Here is your simplified code:
```
type: custom:config-template-card
entities:
  - device_tracker.my_device
card:
  type: grid
  square: false
  cards:
    - type: custom:map-card
      history_date_selection: true
      entities:
        - entity: device_tracker.my_device
    - type: energy-date-selection
  columns: 1
```
