### ISSUE TITLE
Doesn't work at all just shows info as if it wasn't installed

### ISSUE THREAD

**Issue by i00** [iantrich/config-template-card#19]
**Release with the issue:**
1.1.1

**Browser and Operating System:**
Chrome, Windows 10

**Description of problem:**
I have setup many scripts & modules in my frontend but I can't get this to work ... just shows the literal text as if this wasn't installed:

``` YAML
....
- type: module
  url: /local/config-template-card.js?v=1.1.1
....
type: 'custom:hui-markdown-card'
content: "${user}"
....
```
