### ISSUE TITLE
States don't automatically update in the UI, refresh required

### ISSUE THREAD

**Issue by KenCote** [iantrich/config-template-card#21]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** 1.1.1

**Last working release (if known):** 

**Browser and Operating System:**  Chrome (79.0.3945.130 (Official Build) (64-bit)) / Windows 10

**Description of problem:**
Using the below config, I am able to adjust the slider and change the light without any issue, however the brightness is not updated in the UI.  If the light is off, and I slide the slider halfway, the light will come on at 50%, the UI still says "Off."  On refresh, it'll correctly report 50%. This is one of many examples -- state doesn't update on entities wrapped in the config-template-card.
```      
      - type: "custom:config-template-card" 
        entities:
          - sensor.master_bedroom
        card:
          type: "custom:hui-entities-card"
          title: "Ken"
          show_header_toggle: false
          entities:     
          - type: custom:slider-entity-row
            entity: light.bedroom
            name: Lights

```
Doing the same thing with the below config works fine (unwrapping from config-template-card) -- the state is updated immediately after I change the position of the slider, without requiring a refresh.
```
        - type: "custom:hui-entities-card"
          title: "Ken"
          show_header_toggle: false
          entities:     
          - type: custom:slider-entity-row
            entity: light.bedroom
            name: Lights
```
