### ISSUE TITLE
Can we template other attributes?

### ISSUE THREAD

**Issue by glassbase** [iantrich/config-template-card#26]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.1.2
**Last working release (if known):**
n/a
**Browser and Operating System:**
Browsers: Windows - Chrome, HA iOS app
OS: HA Docker

**Description of problem:**
It appears that I can only template name and icon - is that all this card supports? 

Can we template other attributes like entity_picture, etc. I was trying to template an entity_picture on my media_player cards for integrations that do not provide entity_pictures like Android TV / Fire TV.

See above

**Javascript errors shown in the web inspector (if applicable):**
n/a

**Additional information:**
card config i was playing around with:
```
type: 'custom:config-template-card'
variables:
  - states['media_player.bedroom_mibox'].attributes.app_name
entities:
  - media_player.bedroom_tv
card:
  app_name: ${'test app_name'}
  media_title: ${'test media_title'}
  entity: media_player.bedroom_tv
  state: ${'idle'}
  icon: ${'mdi:apple'}
  name: ${'test name'}
  source: ${'test source'}
  type: ${'custom:mini-media-player'}
  entity_picture: ${'/local/images/netflix.jpg'}
```

**Comment by iantrich** [comment]
I am so confused as to what you're trying to achieve here..

**Comment by glassbase** [comment]
Ok yes the config i posted makes no sense on my end goal, but what I was trying to show/test/prove is that the only fields that get overwritten in the card are icon and name.

Is your card supposed to allow templating any attribute?

**Comment by glassbase** [comment]
```
card:
  app_name: '${''test replace app_name''}'
  entity: media_player.bedroom_tv
  entity_picture: '${''/local/images/netflix.jpg''}'
  icon: '${''mdi:apple''}'
  media_title: '${''test replace media_title''}'
  name: '${''test replace name''}'
  type: '${''custom:mini-media-player''}'
entities:
  - media_player.bedroom_tv
type: 'custom:config-template-card'
variables:
  - 'states[''media_player.bedroom_mibox''].attributes.app_name'
```
