### ISSUE TITLE
card not print when use with custom:swipe-card

### ISSUE THREAD

**Issue by vincentDcmps** [iantrich/config-template-card#27]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
since 0.107
**Last working release (if known):**
0.106
**Browser and Operating System:**
Firefox & chromiu

**Description of problem:**
I use config template card to calculate number of point need to minigraph of temperature humidity
since an update the card is not print and I see no error
conflict seem to be with swipe custom card when I remove the swipe card I can see my card and when I remove template card swip work too
you can find yaml file for my card below:

````
card:
  cards:
    - cards:
        - entities:
            - label: 'Nombre de jour a afficher:'
              type: section
            - entity: input_number.days_to_show_temp_graph
              full_row: true
              name: hide_state
              type: 'custom:slider-entity-row'
            - type: section
          show_header_toggle: false
          type: entities
        - color_thresholds_transition: smooth
          entities:
            - entity: sensor.pressure_chambre
              index: 0
              name: pressure chambre
          font_size: 100
          group: false
          hour24: true
          hours_to_show: '${vars[0] * 24}'
          line_width: 6
          points_per_hour: '${2/vars[0]}'
          show:
            extrema: false
            fill: fade
            labels: true
            name: true
            state: true
          type: 'custom:mini-graph-card'
        - cards:
            - color_thresholds_transition: smooth
              entities:
                - entity: sensor.humidity_chambre
                  index: 0
                  name: humidity chambre
              font_size: 100
              group: false
              hour24: true
              hours_to_show: '${vars[0] * 24}'
              line_width: 6
              points_per_hour: '${2/vars[0]}'
              show:
                extrema: false
                fill: fade
                labels: true
                name: true
                state: true
              type: 'custom:mini-graph-card'
            - color_thresholds_transition: smooth
              entities:
                - entity: sensor.temperature_chambre
                  index: 0
                  name: temperature chambre
              font_size: 100
              group: false
              hour24: true
              hours_to_show: '${vars[0] * 24}'
              line_width: 6
              points_per_hour: '${2/vars[0]}'
              show:
                extrema: true
                fill: fade
                labels: true
                name: true
                state: true
              type: 'custom:mini-graph-card'
          type: horizontal-stack
      title: chambre
      type: 'custom:vertical-stack-in-card'
    - cards:
        - entities:
            - label: 'Nombre de jour a afficher:'
              type: section
            - entity: input_number.days_to_show_temp_graph
              full_row: true
              name: hide_state
              type: 'custom:slider-entity-row'
            - type: section
          show_header_toggle: false
          type: entities
        - color_thresholds_transition: smooth
          entities:
            - entity: sensor.pressure_exterieur
              index: 0
              name: pressure exterieur
          font_size: 100
          group: false
          hour24: true
          hours_to_show: '${vars[0] * 24}'
          line_width: 6
          points_per_hour: '${2/vars[0]}'
          show:
            extrema: false
            fill: fade
            labels: true
            name: true
            state: true
          type: 'custom:mini-graph-card'
        - cards:
            - color_thresholds_transition: smooth
              entities:
                - entity: sensor.humidity_exterieur
                  index: 0
                  name: humidity exterieur
              font_size: 100
              group: false
              hour24: true
              hours_to_show: '${vars[0] * 24}'
              line_width: 6
              points_per_hour: '${2/vars[0]}'
              show:
                extrema: false
                fill: fade
                labels: true
                name: true
                state: true
              type: 'custom:mini-graph-card'
            - color_thresholds_transition: smooth
              entities:
                - entity: sensor.temperature_exterieur
                  index: 0
                  name: temperature exterieur
              font_size: 100
              group: false
              hour24: true
              hours_to_show: '${vars[0] * 24}'
              line_width: 6
              points_per_hour: '${2/vars[0]}'
              show:
                extrema: true
                fill: fade
                labels: true
                name: true
                state: true
              type: 'custom:mini-graph-card'
          type: horizontal-stack
      title: exterieur
      type: 'custom:vertical-stack-in-card'
  type: 'custom:swipe-card'
entities:
  - input_number.days_to_show_temp_graph
type: 'custom:config-template-card'
variables:
  - 'states[''input_number.days_to_show_temp_graph''].state'

````
