### ISSUE TITLE
Browser crashes due to error

### ISSUE THREAD

**Issue by petergerdes** [iantrich/config-template-card#30]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
Home Assistant Core - 0.110.1
config-template-card - latest

**Last working release (if known):**
Home Assistant Core - 0.109.6

**Browser and Operating System:**
Mac OS, Chrome & Safari

**Description of problem:**
**Javascript errors shown in the web inspector (if applicable):**

```
[Error] hui-error-card
TypeError: n.setConfig is not a function. (In 'n.setConfig(t)', 'n.setConfig' is undefined)
	n (config-template-card.js:3213:5426)
	O (config-template-card.js:3213:5832)
	render (config-template-card.js:3258:89)
	update (config-template-card.js:2827)
	performUpdate (config-template-card.js:2285)
	(anonymous function) (config-template-card.js:2237)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
[Error] hui-error-card – TypeError: n.setConfig is not a function. (In 'n.setConfig(t)', 'n.setConfig' is undefined) — config-template-card.js:3213:5392
TypeError: n.setConfig is not a function. (In 'n.setConfig(t)', 'n.setConfig' is undefined) — config-template-card.js:3213:5392
	n (config-template-card.js:3213:5426)
	O (config-template-card.js:3213:5832)
	render (config-template-card.js:3258:89)
	update (config-template-card.js:2827)
	performUpdate (config-template-card.js:2285)
	(anonymous function) (config-template-card.js:2237)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
[Error] hui-error-card – TypeError: n.setConfig is not a function. (In 'n.setConfig(t)', 'n.setConfig' is undefined) — config-template-card.js:3213:5392
```

**Additional information:**

**Comment by iantrich** [comment]
Are you using this in a stack by chance?

**Comment by petergerdes** [comment]
No, an image card :)

**Comment by iantrich** [comment]
share the config

**Comment by petergerdes** [comment]
```
       - card:
          aspect_ratio: 0%
          entities:
            - entity: input_boolean.doorbell
          hold_action:
            action: none
          image: '${''/local/snapshot_voordeur.png?time=''+Date.now()}'
          tap_action:
            action: none
          title: Deurbel
          type: picture-glance
        entities:
          - input_boolean.doorbell
        type: 'custom:config-template-card'
```
