### ISSUE TITLE
Hide entity

### ISSUE THREAD

**Issue by andreamastro** [iantrich/config-template-card#38]
I think that would be useful add an option to hide a specific entity if it has not a specific state.
For example:
```
type: 'custom:config-template-card'
variables:
  - states[light.bedroom'].state
entities:
  - light.bedroom
card:
  type: entities
  entities:
    - entity: "${vars[0] === 'on' ? 'light.bedroom' : 'hide_entity'}"
      name: Bedroom light
```
