### ISSUE TITLE
Not being able to see states?

### ISSUE THREAD

**Issue by giuliandenicola1** [iantrich/config-template-card#44]
**Checklist:**
- [ * ] I updated to the latest version available
- [ * ] I cleared the cache of my browser

**Release with the issue:**
1.2.0 HA: 0.115.6

**Browser and Operating System:**
Chrome on windows and android
HA app on android

**Description of problem:**
Tried the "Templated entities example" modified it with my light entity and got a blank page. I opened dev tools -> console 
It seems not to be able to see states.
```
  - path: home
    title: Home
    visible: true
    panel: false
    cards:
      - type: custom:config-template-card
        variables:
          - states['light.bulb_couch_lr'].state
        entities:
          - '${vars[0]}'
        card:
          type: entities
          entities:
          -  entity: '${vars[0]}'
          -  name: "${states[vars[0]].state === 'on' ? 'Light On' : 'Light Off'}"
```
![image](https://user-images.githubusercontent.com/67443916/95016218-d88a6c00-0651-11eb-954a-2e08c7398a0d.png)
