### ISSUE TITLE
Documentation is lacking information

### ISSUE THREAD

**Issue by jmgiaever** [iantrich/config-template-card#53]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):** 0.117.6
**Browser and Operating System:** 86.0.4240.183 (Official Build) (64-bit)/Ubuntu 20.04

**Description of problem:**
Not sure.

**Javascript errors shown in the web inspector (if applicable):**

```
- None
```

**Additional information:**
this dosn't work:
```
      - type: custom:config-template-card
        card: 
          type:  picture-entity
        entities:
          - persons.jmg
```
