### ISSUE TITLE
Auto refreshing of values raising exception

### ISSUE THREAD

**Issue by deemonrider** [iantrich/config-template-card#58]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Windows 10 (Edge, Chrome, Firefox) + Android (Home Assistant APP)

**Description of problem:**
Auto refresh of values doesn't work (initial loading or f5 works). The lovelace entities are auto generated by https://github.com/thomasloven/lovelace-auto-entities

**Javascript errors shown in the web inspector (if applicable):**

```
﻿﻿Uncaught (in promise) TypeError: this._config.entities.forEach is not a function
    at HTMLElement.shouldUpdate (config-template-card.js:3290)
    at HTMLElement.performUpdate (config-template-card.js:2414)
    at HTMLElement._enqueueUpdate (config-template-card.js:2369)
```

**Additional information:**

Lovelace:
```
type: 'custom:auto-entities'
card:
  type: grid
  columns: 6
card_param: cards
filter:
  include:
    - entity_id: /sensor.server_/
      options:
        type: 'custom:config-template-card'
        entities: this.entity_id
        card:
          type: gauge
          entity: this.entity_id
          max: 100
```

**Comment by maltemosler** [comment]
```this._config.entities```:

![image](https://user-images.githubusercontent.com/20888573/105192703-9f123980-5b38-11eb-88c0-9ca6d0ded693.png)

**Comment by maltemosler** [comment]
My bad, entitites needed to be a list...
```
type: 'custom:auto-entities'
card:
  type: grid
  columns: 6
card_param: cards
filter:
  include:
    - entity_id: /sensor.server_/
      options:
        type: 'custom:config-template-card'
        entities: 
         - this.entity_id
        card:
          type: gauge
          entity: this.entity_id
          max: 100
```

But it still doesn't work as expected, is this template card tested with card-type: gauge?  When receiving a new value the animation repeats like I refresh my browser.
![asddfas](https://user-images.githubusercontent.com/20888573/105226487-540c1c80-5b60-11eb-8d9e-5c8ecb7320d0.gif)

**Comment by iantrich** [comment]
Have you tried this without auto-entities? No testing has been done with other custom cards.

**Comment by maltemosler** [comment]
I tired it without auto-entities, same result.

copy paste on my phone doesn't work but with the config below you get this result:
```
type: 'custom:config-template-card'
entities:
  - sensor.xy
card:
  type: gauge
  entity: sensor.xy
  min: 0
  max: 1000
```

**Comment by iantrich** [comment]
I am unable to replicate

**Comment by maltemosler** [comment]
Thats strange.

I reinstalled this card, cleared Cache and tried different browsers.

```
  - title: Testttttt
    path: testttttt
    badges: []
    cards:
      - type: 'custom:config-template-card'
        entities:
          - sensor.fritz_box_7590_packets_sent
        card:
          type: gauge
          entity: sensor.fritz_box_7590_packets_sent
          min: 0
          max: 100000000
```

![asfasfasfasfafsf](https://user-images.githubusercontent.com/20888573/106253627-048cb700-6218-11eb-9066-0d6764fd693b.gif)

Any idea what could lead to this behaviour? Im out of ideas

**Comment by Veuchez** [comment]
Have you found a solution?
I think my problem #60 is the same as yours.

**Comment by maltemosler** [comment]
Nope, sorry. I have still no clue whats going on, this weird refreshes are really annyoing :/

**Comment by iantrich** [comment]
Good news, I figured out how to replicate this. Will see what can be done.

**Comment by kamtschatka** [comment]
Hi

I also had a look at this issue.
Basically, when the state of a sensor changes, the Config-Template-Card will trigger a rerender, which will create a new gauge card. The standard behavior of the gauge card is to show this animation and that is why you are seeing this movement(basically the new gauge card is just going from 0 to this value)

I have a question though:
Why do you need to use the template-card in the first place for this? The sample you provided can be done without the template as well:
```
type: custom:auto-entities
card:
  type: grid
  columns: 6
card_param: cards
filter:
  include:
    - entity_id: /sensor.server_/
      options:
        type: gauge
        entity: this.entity_id
        max: 100
```

Would be interesting to know where exactly you are using the template. I am using this card quite extensively and ran into the issue that recalculating the template is done quite often(basically with any state update), but once the basic templating is done, nothing is updating anymore. Basically I calculate the entity_id of some switches based on a sensor, replace somee strings to shorten them and that's it.
There would not be the need to recalculate ANYTHING after that, and no change in the state of any sensor would change that.
So I am thinking maybee you have the same usecase and it would be possible to just add a config to the card that would only ever update if the config changes?
