### ISSUE TITLE
Cannot template list-card

### ISSUE THREAD

**Issue by viktak** [iantrich/config-template-card#61]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.3.0
**Last working release (if known):**

**Browser and Operating System:**
Windows 10 Pro 64

**Description of problem:**
Trying to template the `list-card' using the following code:
```
  - type: 'custom:config-template-card'
    entities:
      - sensor.earthquakes
    card:
      type: 'custom:list-card'
      title: Earthquakes
      entity: sensor.earthquakes
      feed_attribute: earthquakes
      columns:
        - title: "Time"
          field: '${ time.strftime("%b %d %X") }'
        - title: "Mag."
          field: magnitude
          style:
            - padding-right: 5px
            - padding-left: 5px
        - title: "Dist."
          field: distance
          postfix: km
          style:
            - padding-right: 5px
            - padding-left: 5px
        - title: "Title"
          field: title
          add_link: link
```

Line `field: '${ time.strftime("%b %d %X") }'` causes the whole thing to not render.

`{{ state_attr('sensor.earthquakes','earthquakes')[0].time.strftime("%b %d %X")  }}` in the Template tester renders correctly as `Feb 12 12:03:13`

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I am using the [earthquake](https://github.com/msekoranja/emsc-hacs-repository) integration as a source to the list.
