### ISSUE TITLE
Variable Entities

### ISSUE THREAD

**Issue by yomotherboard** [iantrich/config-template-card#62]
Thank you to all for the great card! I have used this card for a couple things successfully but I haven't been able to dynamically change which entities are displayed. Is it possible to change the entity/entities displayed using a template or variables? Here is my attempt:

```yaml
    cards:
      - type: 'custom:config-template-card'
        variables:
          - "${ 'input_boolean.motion_lights_' ~ states['input_select.room'].state | regex_replace(' ','_') | lower }"
        entities:
          - input_boolean.motion_lights_living_room
          - input_boolean.motion_lights_kitchen
          - input_boolean.motion_lights_pantry
          - input_boolean.motion_lights_mud_room
          - '${vars[0]}'
        card:
          type: entities
          title: Motion Settings
          entities:
            - '${vars[0]}'
```

I don't get any errors, but I also don't get any output. I am trying to make a settings page for a couple rooms.
