### ISSUE TITLE
Support templated icon element inside picture-elements card

### ISSUE THREAD

**Issue by marrobHD** [iantrich/config-template-card#70]
**Is your feature request related to a problem? Please describe.**
I would like to have an icon which could change its icon based on a sensor inside an picture-elements card.

**Describe the solution you'd like**
A way to implement the card working with elements inside picture-elements card.

**Describe alternatives you've considered**
/

**Additional context**

A configuration should look somehow like this:
```yaml
type: picture-elements
image: /local/images/coronavirus_transparent_full.png
elements:
  - type: custom:config-template-card
    element:
      type: picture-elements-icon
      icon: >-
         ${if (states['binary_sensor.virus._weekincidence_rising'].state === 'on')
          'mdi:virus';else 'mdi:virus-outline'}
    style:
      top: 8%
      left: 10%
      color: var(--ha-card-header-color)
```
