### ISSUE TITLE
element style no longer work in 1.3.6

### ISSUE THREAD

**Issue by smonesi** [iantrich/config-template-card#86]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

1.3.6

**Last working release (if known):**

1.3.5

**Browser and Operating System:**

Chrome on Mac OS X

**Description of problem:**

The `style` inside an `element` is no longer properly applied.

Sample code:

```
type: picture-elements
image: >-
  http://hs.sbcounty.gov/CN/Photo%20Gallery/_t/Sample%20Picture%20-%20Koala_jpg.jpg?Mobile=0
elements:
  - type: custom:config-template-card
    entities:
      - time.time
    element:
      type: image
      image: >-
        http://hs.sbcounty.gov/CN/Photo%20Gallery/_t/Sample%20Picture%20-%20Koala_jpg.jpg?Mobile=0
      style:
        background-color: white
        border-radius: 100%
        box-shadow: 0px 0px 0px 2px rgba(255,255,255,1)
    style:
      display: flex
      top: 30%
      left: 30%
      width: 100px
```

1.3.5:
<img width="489" alt="Screenshot 2021-10-06 at 23 59 49" src="https://user-images.githubusercontent.com/63957397/136289547-c951bf78-bbd3-4bde-8373-fc6f4d12ce5a.png">

1.3.6:
<img width="499" alt="Screenshot 2021-10-07 at 00 00 41" src="https://user-images.githubusercontent.com/63957397/136289575-6dd91e2e-cf6a-4229-a759-149eee7f6279.png">

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
