### ISSUE TITLE
History-graph & Logbook are not updated inside config-template-card

### ISSUE THREAD

**Issue by ildar170975** [iantrich/config-template-card#87]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
2021.10.6

**Last working release (if known):**

**Browser and Operating System:**
Chrome, Win10x64

**Description of problem:**
History-graph & Logbook cards are not updated if placed inside `config-template-card`.
The example contains:
- entities card with `input_boolean.flag`
- entity card inside `config-template-card`
- `history-graph` inside `config-template-card`
- `history-graph`
```
    mode: vertical
    cards:
      - type: entities
        state_color: true
        entities:
          - entity: input_boolean.flag

      - type: custom:config-template-card
        entities:
          - input_boolean.flag
        card:
          type: entity
          entity: input_boolean.flag

      - type: custom:config-template-card
        entities:
          - input_boolean.flag
        card:
          type: history-graph
          entities:
            - input_boolean.flag
          hours_to_show: 1
          refresh_interval: 0

      - type: history-graph
        entities:
          - input_boolean.flag
        hours_to_show: 1
        refresh_interval: 0
```
Change the `input_boolean.flag` value and see if graphs are updated.

![image](https://user-images.githubusercontent.com/71872483/137827705-d01b303c-3f6c-401d-b199-02e8bcfae454.png)

The 2nd graph is updated, the 1st graph - not updated:

![image](https://user-images.githubusercontent.com/71872483/137827906-9a49dc6d-5044-49b4-bfd9-741c3a34e4a5.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
