### ISSUE TITLE
entities parameter does not accept variable 

### ISSUE THREAD

**Issue by wrieden** [iantrich/config-template-card#93]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** Master Branch
**Last working release (if known):** unknown
**Browser and Operating System:** chrome 96.0.4664.110, Win 11

**Description of problem:**

entity list based of variables is not working for me.
For example:
```
type: custom:config-template-card
variables:
  STATE_KEYS: Object.keys(states).filter(k => k.startsWith('sensor'))
entities: ${STATE_KEYS}
```
or
```
type: custom:config-template-card
variables:
  STATE_KEYS: Object.keys(states).filter(k => k.startsWith('sensor'))
entities: 
  - ${STATE_KEYS}
```

**Additional information:**

This seems to be an error with the shouldUpdate function, as the evaluation of the Variables is carried out too late.
I've made the following change locally, which solves the problem for me:

old:
```
 if (oldHass) {
    for (const entity of this._config.entities) {
      const evaluatedTemplate = this._evaluateTemplate(entity);
      if (Boolean(this.hass && oldHass.states[evaluatedTemplate] !== this.hass.states[evaluatedTemplate])) {
        return true;
      }
    }
    return false;
  }
```
new:
```
if (oldHass) {
    for (const entity of this._evaluateTemplate(this._config.entities)) {
        if (Boolean(this.hass && oldHass.states[entity] !== this.hass.states[entity])) {
            return true;
        }
    }
    return false;
}
```

**Comment by ildar170975** [comment]
@wrieden 
1. What happens if "entities" are not templated here? I.e. in case of a traditional list of entities.
```
for (const entity of this._evaluateTemplate(this._config.entities)) {
```
2. Suggest you to create a PR for this proposal!

**Comment by ildar170975** [comment]
Tested the proposed [fix](https://github.com/iantrich/config-template-card/issues/93#issue-1091697084) locally.
It causes constant flickering - even when a monitored entity is not changed.
```
type: custom:config-template-card
entities:
  - sun.sun
card:
  type: history-graph
  entities:
    - sun.sun
```
This card erratically flickering every several seconds.

**Comment by PaulSD** [comment]
The problem here is that the change above only works if `entities` (as a whole) is a template; It does not work if `entities` is a list (that may or may not contain templates).  Fixed in #153.

**Comment by ildar170975** [comment]
1.3.7-beta.1
This code from the 1st comment of @wrieden  seems to work:
```
type: custom:config-template-card
variables:
  STATE_KEYS: Object.keys(states).filter(k => k.startsWith('light'))
entities: ${STATE_KEYS}
card:
  type: entities
  entities: ${STATE_KEYS}
```
Closing as implemented with https://github.com/iantrich/config-template-card/pull/153.
Please let us know if someone sees any glitches.
