### ISSUE TITLE
Custom element doesn't exist: config-template-card

### ISSUE THREAD

**Issue by jmcollin78** [iantrich/config-template-card#96]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.3.6

**Last working release (if known):**
-

**Browser and Operating System:**
Chrome. MacOS Monterey 12.1

**Description of problem:**
After successful installation with HACS, I try to use the card. I manually insert the following card code:

```
type: custom:config-template-card
entities:
  - light.lampe_entree_1
card:
  type: entities
  entities:
    - entity: light.lampe_entree_1
      name: Ca roule ?

```
And Whatever I do I've got the error:
```
Custom element doesn't exist: config-template-card.
type: custom:config-template-card
entities:
  - light.lampe_entree_1
card:
  type: entities
  entities:
    - entity: light.lampe_entree_1
      name: Ca roule ?

```

**Javascript errors shown in the web inspector (if applicable):**
No specific errpr
```

```

**Additional information:**
