### ISSUE TITLE
map-card inside config-template-card is missing most of the time

### ISSUE THREAD

**Issue by noxhirsch** [iantrich/config-template-card#99]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2022.3.X (from 2022.3.0b0 to 2022.4.0.dev20220309)

**Last working release (if known):**
2022.2.9

**Browser and Operating System:**
Current version of Edge Chromium & Firefox - both on Win 11

**Description of problem:**
If using a `map-card` inside `config-template-card`, it is missing most of the time on first load. It seems to appear, if the entity gets an update, if you edit the card or if you come from another dashboard.

Tested on my main HA instance and on an empty second instance with different HA versions (as listed above) and without any other frontend cards/modifications.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Example config (as minimalistic as possible to eliminate config errors):

```
type: custom:config-template-card
entities:
  - person.nico
variables:
  - states['person.nico'].state
card:
  type: map
  entities:
    - entity: person.nico
```
The card should be visible here:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/30938717/157408556-b82710da-b4f2-4088-9a14-f629e52ff4b0.png">
And here:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/30938717/157408609-db16493c-3dbc-4296-9538-c715494c9369.png">
It appears when you open the editor:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/30938717/157408658-7a9014b7-b38f-48be-8b10-21056fd9b909.png">

**Comment by idoaflalo** [comment]
Experiencing the same problem

**Comment by ildar170975** [comment]
Confirm the same with a bit more simple code:
```
type: custom:config-template-card
entities:
  - person.ildar
card:
  type: map
  entities:
    - entity: person.ildar
```
